version: "3.1"
services:

    mysql:
      image: mysql:latest
      working_dir: /app
      volumes:
        - .:/app
      environment:
        - MYSQL_ROOT_PASSWORD=adminrootpass
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=adminpass
        - MYSQL_DATABASE=enjoybooks
      ports:
        - "3306:3306"

    webserver:
      image: nginx:alpine
      working_dir: /app
      volumes:
          - .:/app
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    rabbitmq:
      build: phpdocker/rabbitmq
      ports:
        - 15672:15672
      environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin

    php-fpm:
      build: ./phpdocker/php-fpm
      working_dir: /app
      volumes:
        - .:/app
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

    hub:
      image: selenium/hub:3.11.0
      ports:
        - 4444:4444
    chrome:
      image: selenium/node-chrome:3.11.0
      depends_on:
        - hub
      environment:
        - HUB_HOST=hub
        - HUB_PORT=4444
      # ports:
      #     - 5900:5900