settings:
    index:
        # single node, no sharding
        number_of_shards: 1
        number_of_replicas: 0
mappings:
    dynamic: false # disable dynamic mapping
    properties:
        title: 
            type: text
        author:
            type: text
            